### ISSUE TITLE
Update pre_ scripts using prep_example and using new crs format

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#132]
The `sf` pacakge v0.9-0 has moved to a new `crs` format. [Detail here](https://www.r-spatial.org/r/2020/03/17/wkt.html). I've already updated `geobr` tests to conform with the new format. However, we need to make changes to the `pre_` scripts, and perhaps check on our data sets that are saved already.

**Comment by rafapereirabr** [comment]
- [ ] read_amazon
- [ ] read_biomes
- [ ] read_census_tract
- [ ] read_conservation_units
- [ ] read_country
- [ ] read_disaster_risk_area
- [ ] read_health_facilities
- [ ] read_immediate_region
- [ ] read_indigenous_land
- [ ] read_intermediate_region
- [ ] read_meso_region
- [ ] read_metro_area
- [ ] read_micro_region
- [ ] read_municipal_seat
- [ ] read_municipality
- [ ] read_region
- [ ] read_semiarid
- [ ] read_state
- [ ] read_statistical_grid
- [ ] read_urban_area
- [ ] read_weighting_area

**Comment by rafapereirabr** [comment]
For out short term necessities, I have just saved all `geobr` data sets using the fxed `crs` information.

**Comment by rafapereirabr** [comment]
@PedroJorge7 , could you please tick the boxes above of the preps you have revised?

**Comment by PedroJorge7** [comment]
Hi @rafapereirabr .

I've already changed this for all the preps, but I didn't checked the code for municipality, micro and meso because I'm waiting for some fixes.

But when I've checked if it was everything all right I found some errors, like:

"> years = getURL(url_h, ftp.use.epsv = FALSE, dirlistonly = TRUE)
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to geoftp.ibge.gov.br port 21: Timed out"

For prep country I found this message:

">   parallel::parLapply(cl, years, get_country)
Error in checkForRemoteErrors(val) : 
  22 nodes produced errors; first error: método não aplicável para 'st_coordinates' aplicado a um objeto de classe "NULL"

**Comment by rafapereirabr** [comment]
In what `prep_` script did this error occur?

**Comment by PedroJorge7** [comment]
From the files that I tested:

municipal_seat
metro_area
