### ISSUE TITLE
Create a single intro Vignette 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#146]
It would be important to have a single intro Vignette for both Python and R, or at least a Vignette  that is very similar in both languages.  This is the current [intro Vignette in R](https://cran.r-project.org/web/packages/geobr/vignettes/intro_to_geobr.html). I

**Comment by jvfe** [comment]
Hi! Thank you for your project! I've used geobr in the past for some personal/university projects and wanted to contribute. 

This issue seems straightforward so I'll try solving it, if that's not a problem. From what I understood, it would be a python jupyter notebook equivalent of the current R vignette so I'll get to work.

**Comment by rafapereirabr** [comment]
Hi Joao. Thanks for your help with this. @JoaoCarabetta , could please have a look the Vignette written by @jvfe ?
