### ISSUE TITLE
Creation of a shapefile for Regional Health

### ISSUE THREAD

**Issue by d116626** [ipeaGIT/geobr#149]
It would be possible to create a new load dataset for health regions. [Here](http://www.saude.sp.gov.br/ses/institucional/departamentos-regionais-de-saude/regionais-de-saude) is an example of this division. 

Thank you very much for this package, it has been very useful in my analysis. (;

**Comment by rafapereirabr** [comment]
Hi Diego, thanks for the suggestion. We have already started building a function to download health regions using the data from the Ministry of Health. It might take a few more weeks before we publish this. In the short run, you could probably download the data directly from the original source. 

@PedroJorge7 , could you share here the link to the data source please ?

**Comment by PedroJorge7** [comment]
Hi Diego. As @rafapereirabr commented, we are working on that. We can put this option in geobr for all the avaliable years that DATASUS makes available. But if you need this information now, we downloaded these maps from the datasus website: ftp://ftp.datasus.gov.br/territorio/mapas. However, these files are in .MAP file and you'll need to convert them into a shapefile to use in R. To convert this file type I normally use TABNET (DATASUS software) to convert into a file that I can use in QGIS software and then transform in Shapefile. This can't be possible in R, because in TABNET doesn't have any options that faciliate to read in R.

This process seems a little complicated and that is why we are working to make geobr facilitate this use. If you have any questions about these processes I can help you :)

**Comment by JoaoCarabetta** [comment]
Might help 
https://github.com/RodrigoMenegat/contornos-regionais-de-saude 
@RodrigoMenegat

**Comment by rafapereirabr** [comment]
Hi all. I got some ~procrastination~ time today and created a `read_health_region()` function. It is already working in the dev version of `geobr` for `R`. Please give it a go and let us know what you think.

```
# install dev version
  utils::remove.packages('geobr')
  devtools::install_github("ipeaGIT/geobr", subdir = "r-package")
  library(geobr)

# read health regions
hr <- read_health_region()
```

**Comment by PedroJorge7** [comment]
Hi Rafael. If you need help just talk :)

Just a suggestion, put the default in the year 2013. I think that most people use the last year

**Comment by rafapereirabr** [comment]
> Hi Rafael. If you need help just talk :)
> 
> Just a suggestion, put the default in the year 2013. I think that most people use the last year

The default year is 2013, the latest available.
