### ISSUE TITLE
New Data: Macrorregiões de Saúde

### ISSUE THREAD

**Issue by marcelamz** [ipeaGIT/geobr#219]
Hello, 

I would like to suggest a new database / function for the health macro-regions divisions. In the package there is a function with the health regions, is there any reason why the macro-regions are not included?

The map files are available on the [DATASUS website](http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1&acao=33&pad=31655).
It is not very clear how the updates are made, which can be a problem since the changes are not unified.

Let me know what you think, I’m open to contribute!

Thanks

**Comment by rafapereirabr** [comment]
Hi @marcelamz . Thank you for opening this issue. We only included the health regions (not the macro regions) because we thought it was the most commonly used. If you want to, I think we could include the macro-regions divisions. This is how we did to include the health regions. I believe the process to include macro-regions will be pretty similar.

**Data download**
I manually downloaded the health regions from the DataSUS ftp on this lik [ftp://ftp.datasus.gov.br/territorio/mapas/](ftp://ftp.datasus.gov.br/territorio/mapas/). I believe the ftp and the link you shared probably have the same files. As you will see, the ftp link has several `.zip` files for each state and year. Each `.zip` file has several `.MAP` files. I'm not entirely sure, but I believe that the macro-region files are the ones named `_macsaud*.MAP`. Could you please confirm that?

**Data cleaning**
We use [this script here](https://github.com/ipeaGIT/geobr/blob/master/r-package/prep_data/prep_health_region.R) to clean and organize the `_regsaud*.MAP` files.  I believe the process to clean macro-regions will be pretty similar.

**Create function**
We should probably reflect on wheter it makes sense to have a separate function, one for `health regions` and another one for macro-regions`. Ideally I would think of a single function where users can set a parameter to decide which regionalization scale they want to download. However, I need to understand a bit better the difference between health regions and macro regions from a planning point of view. Any knowledge you could share here would be much appreciated.

**Comment by marcelamz** [comment]
Hi, thanks for the reply!
I see. I didn't know about this regionalization until I started working with COVID-19 data. 

About the data download, the files names are exactly what you said. :)

Well, I am not in the health field, but I did some research and from what I understood macroregions are created according to the need for better distribution of health equipment and planning. 
I found this excerpt in this [document](http://bvsms.saude.gov.br/bvs/publicacoes/regionalizacao_assist_saude.pdf):

> “A assistência de alta complexidade será programada no âmbito regional/estadual, e em alguns casos macrorregional, tendo em vista as características especiais desse grupo – alta densidade tecnológica e alto custo, economia de escala, escassez de profissionais especializados e concentração de oferta em poucos municípios.”

After a quick skim through the states, it is possible to see that in the cases where the macroregions are not unique, they're identical to the health regions or they encompass the entire state in a single macroregion.

I think that a single function would be very convenient. 

Let me know what you decide!

**Comment by rafapereirabr** [comment]
Thank you @marcelamz . So it seems that there are no differences between health regions and the macro-regions. Is that correct?

**Comment by pedrovma** [comment]
The decentralization in the SUS is based primarily on two different levels, according to the complexity of health care. The health regions are the smaller geographical units and were created to organize the provision of less complex health services. The health macro-regions are an aggregation of those, created to organize the flow between lower and higher levels of complexities. The creation of health macro-regions aggregated the 438 health regions that existed then into 118 macro-regions. You can find more info on this process here:
http://www.conass.org.br/conas-informa-n-66-publicada-resolucao-cit-n-37-que-dispoe-sobre-o-processo-de-planejamento-regional-integrado-e-organizacao-de-macrorregioes-de-saude/

States can reform their regionalization plan. As an example, in 2020 Minas Gerais created an additional macro-region, summing up 14 macro-regions and 89 health regions.

![image](https://user-images.githubusercontent.com/4238922/111303764-aa16b100-8633-11eb-87e2-7215d90e00f1.png)

**Comment by marcelamz** [comment]
Here are some examples from the Base Territorial database:

![ex regioes e macros](https://user-images.githubusercontent.com/51302399/111337761-1c4bbd80-8655-11eb-8bb6-bfc7d5d1b5e9.JPG)

**Comment by rafapereirabr** [comment]
Hi @marcelamz and @pedrovma ,

Thanks for the clarifications. I have finished processing and cleaning the data. We need now to settle on the function documentation. I've drafted this brief description that explains the macro regions of health. Ideally, we should add a sentence or two about the health regions. could you please suggest something?

```
#' Download spatial data of Brazilian health regions and health macro regions
#'
#' @description
#' Macro health regions are used to guide the regional and state planning of high complexity
#' health services. These services involve larger economics of scale and are concentrated in
#' few municipalities because they are generally more technology intensive, costly and face
#' shortages of specialized professionals.
#'
```

I'm also editing the function to have a new `Logic` argument called `macro`. If `macro=TRUE`, the function downloads macro regions data. If `FALSE`, then health regions are downloaded. My question to you is, what do you think should be the **Default** parameter?

**Comment by marcelamz** [comment]
Hi @rafapereirabr,
Awesome!
I wish I could have helped you!

Regarding the definition, wouldn't it be interesting to include something that like: formed by one or more health regions?

I think the default parameter should be `macro = FALSE`, since all states have unique health regions but not necessarily unique macro health regions.

 Also, I was wondering if the function also includes the updates over the years.

**Comment by rafapereirabr** [comment]
Yep, the function allows one to download the health regions data for any of the following years: 1991 1994 1997 2001 2005 2013. Are there more recent data?

**Comment by marcelamz** [comment]
Perfect! I meant for the macro regions, but I don't know if the changes are available in the database

**Comment by rafapereirabr** [comment]
Ok. This has been implemented in the dev version of `geobr`.
