### ISSUE TITLE
Using plotly with geobr data - python

### ISSUE THREAD

**Issue by FranciscohAlpa** [ipeaGIT/geobr#256]
Hello how are you ?
I saw that in R it is possible to use plotly with the data from the geobr package, but I didn't find anything in python. Would you help me ?

**Comment by rafapereirabr** [comment]
Hi @FranciscohAlpa . It's fairly straightforward to use the plotly package in both R and in Python. There are quite a few tutorials and examples with code to do that , [see this gallery for example](https://plotly.com/python/maps/ ).

The plotly package should work with data from geobr, but let us know if you find any problems. For now I'm closing this issue since it is not directly related to an issue with geobr.
