### ISSUE TITLE
Time for a Julia version? :)

### ISSUE THREAD

**Issue by juliohm** [ipeaGIT/geobr#264]
We have developed GeoTables.jl and GADM.jl over the years to download spatial geometries for any place in the world by name. I would be nice to have a GeoBR.jl package in Julia as well. 💯

**Comment by rafapereirabr** [comment]
Hi Julio. That could be a great idea. Could you please point me to these Julia packages you have created already?

**Comment by juliohm** [comment]
Here are the two packages I mentioned:

- https://github.com/JuliaEarth/GeoTables.jl
- https://github.com/JuliaGeo/GADM.jl

The former uses the latter and you can watch it in action in my JuliaCon 2021 talk:

https://youtu.be/75A6zyn5pIE

A GeoBR.jl would be a nice addition in the sense that it is a data set curated by IBGE specifically for Brazil boundaries, correct? I learned about the project today, didn't have time to investigate it carefully yet.

**Comment by rafapereirabr** [comment]
Hi @juliohm , thanks for the links. It looks somewhat similar with Python, so assuming it's possible to read spatial data sets in `geopackage.gpkg` format, building a Julia version of `geobr` should be relatively simple. We should probably schedule a call to discuss this. Perhps @JoaoCarabetta might wanna join us.

Please mind, however, that `geobr` is not limited to IBGE data. We cover multiple official spatial data sets from various sources. Naturally, IBGE is the largest producer of spatial data in Brazil but we also cover data from INEP, DataSus, FUNAI, MMA etc.

Another important point you will note in our documentation. `geobr` does not simply store raw original data sets. One of the most important contributions of `geobr` is to preprocess the data for various years in order to harmonize attributes, projection and fix eventual topology issues. This is very important to make all data sets in `geobr` compatible and easy to manipulate for the end user

**Comment by juliohm** [comment]
That is great @rafapereirabr , let's set a call next week to discuss the most straightforward steps to get geobr working in Julia. We can read gpkg files through GDAL, and that is what GeoTables.jl does behind the scenes. If you store these datasets on a server, we can even setup a GeoBR.jl package that downloads data for specific regions of the world on demand like we did with GADM.jl.

**Comment by JoaoCarabetta** [comment]
Hey, let me know when you are meeting, I'll try to fit it into my schedule.

But, developing a Julia package should be quite straightforward if you can read gpkg. Just copying the python package structure might solve it.

**Comment by juliohm** [comment]
How does tomorrow morning sound to you? 11am BRT? My email is on my GitHub profile, appreciate if you can send an invitation with a proposal time.

**Comment by juliohm** [comment]
For anyone interested in the geobr dataset within Julia, you can use the GeoArtifacts.jl module: https://github.com/JuliaEarth/GeoArtifacts.jl?tab=readme-ov-file#geobr

Copying one example below:

![Image](https://github.com/user-attachments/assets/48488c80-444b-4fc9-be5d-9a0b6c1cf99f)

Thank you for working on this dataset, and for the many other datasets you are curating in Brazil 🇧‍🇷 💯

**Comment by juliohm** [comment]
Good idea! Done here: https://github.com/JuliaEarth/GeoArtifacts.jl/commit/a17dd31cf332b23edadcc7848262bb7ab8ac21c2

Submitted a patch release for registration, the bot should merge in ~15min: https://github.com/JuliaRegistries/General/pull/127444
