### ISSUE TITLE
Create server mirrors

### ISSUE THREAD

**Issue by JoaoCarabetta** [ipeaGIT/geobr#276]
Given the current instability of IPEA server, it might be a good ideia to have mirrors.

Other organizations can host `geobr` that can be used if the main server fails.

I can modify the python package to support this kind of behavior. @rafapereirabr can implement it on R?

The organization Base dos Dados is willing to support a mirror with a 1 month update rate. 

@rafapereirabr let me know what you think. If approved, I can start to work on it ASAP.

**Comment by WeiZhiWater** [comment]
Problem connecting to data server.

**Comment by rafapereirabr** [comment]
I have now finished uploading all files from **geobr** as assest to release [v1.7.0 on github](https://github.com/ipeaGIT/geobr/releases/tag/v1.7.0). This means that all files are now simultaneously stored in two servers: our own server at Ipea and on github. For example, the `amazonia_legal.gpkg` can be found either of the links below.
- "https://www.ipea.gov.br/geobr/data_gpkg/amazonia_legal/2012/amazonia_legal.gpkg"
- "https://github.com/ipeaGIT/geobr/releases/download/v1.7.0/amazonia_legal.gpkg"

I have also made changes to the `download_gpkg()` and `download_metadata()` functions so that **geobr**  now downloads the data from Ipea. In case the Ipea link is off line for some reason, then the package tries to download the data from Github. For users, the effect of this change is that the package is much more stable and less vulnerable to instabilities in Ipea’s data server connection.

@JoaoCarabetta , let me know if you would like my help to implement these changes to the Python version of **geobr**.

**Comment by rafapereirabr** [comment]
this issue has been fixed already
