### ISSUE TITLE
Create function tests for Python

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#322]
It might be a good idea to use the [pytest testing system](http://doc.pytest.org/en/latest).

**Comment by vss-2** [comment]
Hello, I would be happy to help!

Pytest offers lots of features to improve testability like [fixtures](https://doc.pytest.org/en/latest/how-to/fixtures.html), [parameters decorators](https://doc.pytest.org/en/latest/how-to/parametrize.html) and [marks](https://doc.pytest.org/en/latest/how-to/mark.html).

Given that most tests are already written and use the default `assert` function (which integrates seamlessly with Pytest), I imagine that the suggestion is to modify the tests structures in a manner such as:
* Split existing functions (with various `assert`s) into more specific ones with detailed parameters and error description/logs

Did I get it correctly? If no, what would be the desired improvements?

**Comment by rafapereirabr** [comment]
Hi @vss-2 . Thanks for your help. Yes, we already have some tests. It would be great to integrate the Python tests with code coverage and github actions. This way, we would (1) have a better understanding of how much of geobr Python code is tested and, (2) more importantly, to have automated checks on commits and pull requests to check if they don't break the Python package. 
I assume Pytest would be a simple way to do this. rigth ?

**Comment by vss-2** [comment]
Absolutely right, I hadn't noticed Python package was missing test coverage. 
Although I have limited experience with GitHub Actions, I am committed to implement them in my geobr fork. 
As soon as I successfully complete the setup (or need some help, hahah), I will notify here.

**Comment by vss-2** [comment]
Hello, after an extensive solving dependecy issues,
I've succesfully established this [stable workflow](https://github.com/vss-2/geobr/actions/runs/5941494684) . Before pull-requesting I would like to highlight these two changes:
* I've updated [Shapely](https://pypi.org/project/shapely/1.2.18/#history) (1.7.0 -> 1.8.1) and [Geopandas](https://pypi.org/project/geopandas/#history) (0.7 -> 0.11.0) as they were outdated. This was causing broken dependencies across all operating systems (Windows, Linux, MacOS) on [Python 3.9 or above ](https://github.com/vss-2/geobr/actions/runs/5940669320) but not in Python 3.8 (probably they last supported version);
* The `list_geobr()` function [here](https://github.com/ipeaGIT/geobr/blob/691cb3bdeabb8d5379be8370afeab768b639ee87/python-package/geobr/list_geobr.py#L19) uses [pd.read_html()](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html) which requires BeautifulSoup4 and html5lib (were also added to `requirements.txt`). Initially, this test was failing in all environments. Turns out (some error warned me) the current implementation of BeautifulSoup doesn't fetch and download HTML files, so I've [modified this way](https://github.com/vss-2/geobr/commit/f3a054a87b652eb8181b1814ea562a6e5f1a3db6) to maintain the expected behavior;

The current workflow ([Python-CMD-check](https://github.com/vss-2/geobr/blob/90019b9532a5fa38f94899096892d56f2c5e9916/.github/workflows/Python-CMD-check.yaml)) is configured to:
* Check `python-package/tests/` for every push event on any branch;
* Run test job on the latest versions of: Ubuntu, MacOS and Windows;
* For each OS: run tests using Python version 3.9 (*discuss further);
* Install specific dependencies (step made specifically because shapely sometimes requires OS-native GEOS lib);
* Install pip requirements.txt, save dependencies and start pytest/coverage;
* Upload test-results.txt containing coverage info to workflow page (currently we're at 88% total coverage 🥳);

I would like to know what other Python versions should I add to testing workflow. My intention was to add versions from 3.8 to 3.11 (current maintened versions).

**Comment by rafapereirabr** [comment]
Hi @vss-2 . This looks great! thanks so much. This is a great contribution to make the Python version of geobr more robust. Regarding the versions of Python that should be tested, testing versions from 3.8 to 3.11 is fine. Please go ahead and open the PR.

**Comment by vss-2** [comment]
Hello, I'm about to submit the PR.
To provide context: I was conducting the [final tests](https://github.com/vss-2/geobr/actions/runs/5999791708) before submitting the pull request. 
It achieved 10 successes and encountered 2 errors due to an unavailable library for Python 3.11 for MacOS and Ubuntu, which I subsequently addressed. 
During this experiment, the tests took from 5 minutes to 1 hour to execute, possibly due to the increasingly load on IPEA server. 

Shortly after solving the 2 errors, I submitted [the definitive test](https://github.com/vss-2/geobr/actions/runs/6001192554) and it encountered failures on all versions of MacOS and Ubuntu, this time related to the server (Windows did not present any errors because its data is cached somewhere). 

I believe these fails are still related to issue #312 , that is: the current code breaks before trying to reach data from mirrors. 

To ensure that no one experiences lag in their work (due to the server workload), later tonight I will submit one more test run.

**Comment by vss-2** [comment]
Further follow-up:
Last night, I attempted to run the failed jobs. By default, GitHub Actions suggests running all 8 failed executions at once, but as soon as they try downloading the .gpkg files, they failed. Might be IPEA's firewall blacklisting this "suspicious" dozens of same-source requests or GitHub internal tools avoiding network bottleneck. 
Therefore, I proceeded to manually run them one after the other, which is why there are records of 9 running attempts. 
In the end, all executions were successful.

**Comment by rafapereirabr** [comment]
Thank you very much for all the effort, @vss-2 ! I'm accepting th PR now. After merging this PR, we can continue collaborating on other issues with the Python version of geobr. Your contribution is much appreciated !

**Comment by rafapereirabr** [comment]
Hi @vss-2. This issue has been solved, right?

**Comment by vss-2** [comment]
Hello, yes it's solved and may be closed :smile:

**Comment by rafapereirabr** [comment]
thanks!
