### ISSUE TITLE
Suggestions for read_conservation_units()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/geobr#66]
I have two suggestions related to #60.

1) As there is only one date available, it could be the default value for the argument in order to allow simply writing:

```R
conserv<- read_conservation_units()
```

2) I could not save the downloaded data using `sf::write_sf()` directly because there are different geometry types. One suggestion is to to convert everything to MULTIPOLYGON when preparing the data:

```R
conserv<- read_conservation_units(201909)
sf::write_sf(conserv, "data.shp") # Error: Attempt to write 
# non-polygon (MULTIPOLYGON) geometry to POLYGON type shapefile
unique(sf::st_geometry_type(conserv)) # [1] MULTIPOLYGON       GEOMETRYCOLLECTION
conserv <- sf::st_cast(conserv, "MULTIPOLYGON") # this could be used in prep_data
sf::write_sf(conserv, "data.shp") # now works properly
```

The call to `sf::st_cast()` above produces four warnings ("only first part of geometrycollection is retained"). These are possibly a subset of the five objects that are represented as "LineString" or "MultiLineString" in the rda file. Possibly some of them do not have the same starting and ending points (as it is required for polygons but not for lines). It would be interesting to visually check these objects.

**Comment by rafapereirabr** [comment]
Thanks for the heads up. Both issues have now been fixed.

The second problem was occuring in the `prep_data` scrip. 

The orinal data is read as `MULTIPOLYGON` but for some reason a few conservation units were converted into `GEOMETRYCOLLECTION` when we ran the code below:
```
# Make any invalid geometry valid # st_is_valid( sf)
temp_sf <- lwgeom::st_make_valid(temp_sf)
```

What I did to solve the problem was to include the line of code you suggested after calling `lwgeom::st_make_valid()`
