### ISSUE TITLE
Defaulting code_xxxx="all"

### ISSUE THREAD

**Issue by pedrovma** [ipeaGIT/geobr#77]
I would like to suggest adding code_xxxx="all" as default in all functions, since having to explicitly state this whenever changing between micros, mesos and ufs is not very nice.

**Comment by rafapereirabr** [comment]
thanks for the suggestions, Pedro! I believe we will try to incorporate them into `geobr` in the next couple of months

**Comment by rafapereirabr** [comment]
This has been implemented in the dev version for pretty much all functions. The only exceptions are the `read_statistical_grid` and `read_census_tract`. These two function do take a really long time to load the data for the whole country and it might crash R due to memory limits, so the user must be more 'aware' about her choice here.
